### ISSUE TITLE
Feature Request: Take Down This Socialist Free ETC Branded Marketing BS

### ISSUE THREAD

**Issue by developerkevin** [ethereumclassic/tweets-etc_network#68]
**What’s missing?**

**Well, it seems that honor and integrity appear to be missing among trusted third party developers seeking "official" ETC Branded marketing to sell / promote / bring awareness or anyone of the responsibilities a community manager, marketer, communications manager, or content manager should be doing for the specific project. This seeming entitlement for free marketing efforts on behalf of an public, open source project  has begun to overflow. PR and Marketing efforts solely relies on which project is seeking such services. Dexaran proposed this exact idea some years ago and it was met with a basic fuck no. Quite frankly I agree with that same sentiment. Its not anyone but the project's developers, contributors, or volunteers to do the work.**

I describe it like this: take this socialist bullshit down and **have projects, resources, volunteers, contributors or anyone who is seeking such services to either A. create a marketing strategy, and related efforts themselves or B. pay someone who has expertise and knowledge in the area.** 

**Why?**

I can't believe I really have to explain why. **Because for god sake it invites trusted third parties into privileged areas not meant for their marketing, tweeting, blog posting, or use of any necessary platform let alone an ETC branded platform which is disgusting and disingenuous. It also invites unnecessary liability onto a project that praises itself on being trust minimized. Do the fucking work yourself**. I run my own independent social media on my own dime still for so many reasons but for christ's sake the main one to remain trust minimized. Who's idea was this? 

Egregious entitlement for free marketing services on behalf of trusted third parties done so by and on ETC branded platforms and communication channels. I'm facing a lack of integrity for the platform these trusted third party devs and projects are built on, inviting unnecessary potential scams and security holes onto the officially branded website!

**Alternatives you tried**

Doing it myself, successfully creating my own accounts, using actual plans, data, and tools not winging my marketing, adding potential security risks, misleading end users! I've had incredible success regarding doing this on my own measured with the KPIs that matter. Not amount of followers. 

Christ, Look at Donald. Donald has created probably dozens of successful social media accounts, on his own dime, on his own time, for the sake of the fucking blockchain, not the trusted third parties built on top of it. **And it is completely unprofessional looking, off-strategy, appears to have no sense of plan or direction besides look at this project, oh and did you notice its displayed on a platform called ETC_Network. Completely misleading and disingenuous imo. Not to  mention this likely breaks several of Twitter's own term's and policies.... specifically hmmmm account / platform manipulation!** 

I just fucking did. Do it yourself or pay someone to do it for your private project. For fucks sake need I say more about Donald, Etherplan, Tokenhash, immmutable samourai, etclogic and all the successful KPIs he's driven to this project on his own dime and own time? Show this project some respect and stop using any ETC branded asset for your project's sake. This makes me utterly sick to my stomach. Hey lets just add a list of internet people who we trust to be kind and forsake any self interest and list them on the fucking official website, not some little marketing channel, the goddamn branded, official website! Wouldn't that be a great idea.

**Comment by developerkevin** [comment]
I'll fight till the bitter end to protect this project. It's one of two out of 5,000 that are not scams.

**Comment by OmniEdge** [comment]
Hey Kevin, There is a current issue discussing what rules to adhere for twitter together. Your thoughts and constructive feedback are welcome.

 https://github.com/ethereumclassic/twitter-together/issues/15

**Comment by w1g0** [comment]
The input you bring is really valuable because I share the same sentiment, although the intention wasn't like how it shows. So to avoid the miscommunication we first need better rules. I totally agree the way it works today is not the way forward.
That being said, there's no official in ETC so that closing point is invalid. Great to have you back and with passion!

Also the fact that there are 3rd party websites on the internet that shows which apps are active on ETC could make the app section on the .org website obsolete and relay any form of responsibility. That way the website could focus more on other important topics.

**Comment by IstoraMandiri** [comment]
@developerkevin please could you give some examples of the content you find questionable?

Thanks!

**Comment by IstoraMandiri** [comment]
https://twitter.com/eth_classic/status/1573045351744872448#m

https://twitter.com/eth_classic/status/1519257798491615232#m

https://twitter.com/eth_classic/status/1519219762550624256#m

![image](https://user-images.githubusercontent.com/1696942/192175158-9e501315-6fcb-4a7d-89ae-7a28a8ce46bc.png)

![image](https://user-images.githubusercontent.com/1696942/192175119-a7af9d54-10d9-4fda-8b03-f0bfec956983.png)

![image](https://user-images.githubusercontent.com/1696942/192175095-cfd95d8b-ccff-404b-b69d-c8444f16de08.png)

**Comment by IstoraMandiri** [comment]
Also please don't pin issues like this unilaterally if this is your first contribution.

![image](https://user-images.githubusercontent.com/1696942/192177066-af9dcb75-2bbb-4edf-8bfa-398adbd18e0e.png)

**Comment by gitr0n1n** [comment]
You might have missed this disclaimer in Discord, so I posted it in github. Apologies for not also posting in the repo on the 17th as well. @IstoraMandiri decided to work the kinks out in the open.
https://github.com/ethereumclassic/twitter-together/issues/70

I believe we've talked about running a tweepy script and purging all history on this account and it likely makes sense to do so once the initialization is complete. Currently there are many centralized needs while @IstoraMandiri figures out how to decentralize processes.

**Comment by Bolsa-BOMS** [comment]
> I'll fight till the bitter end to protect this project. It's one of two out of 5,000 shitcoin projects that are not scams.

Oi! Eu estou lendo! I'm reading and I'll answer you!

**Comment by Bolsa-BOMS** [comment]
> I'll fight till the bitter end to protect this project. It's one of two out of 5,000 shitcoin projects that are not scams.

Oi! Eu estou lendo! I'm reading and I'll answer you!

**Comment by Bolsa-BOMS** [comment]
*What’s missing?*

*Well, it seems that honor and integrity appear to be missing among trusted
third party developers seeking "official" ETC Branded marketing to sell /
promote / bring awareness or anyone of the responsibilities a community
manager, marketer, communications manager, or content manager should be
doing for the specific project. This seeming entitlement for free marketing
efforts on behalf of an public, open source project has begun to overflow.
PR and Marketing efforts solely relies on which project is seeking such
services. Dexaran proposed this exact idea some years ago and it was met
with a basic fuck no. Quite frankly I agree with that same sentiment. Its
not anyone but the project's developers, contributors, or volunteers to do
the work.*

I describe it like this: take this socialist bullshit down and *have
projects, resources, volunteers, contributors or anyone who is seeking such
services to either A. create a marketing strategy, and related efforts
themselves or B. pay someone who has expertise and knowledge in the area.*

*Why?*

I can't believe I really have to explain why. *Because for god sake it
invites trusted third parties into privileged areas not meant for their
marketing, tweeting, blog posting, or use of any necessary platform let
alone an ETC branded platform which is disgusting and disingenuous. It also
invites unnecessary liability onto a project that praises itself on being
trust minimized. Do the fucking work yourself*. I run my own independent
social media on my own dime still for so many reasons but for christ's sake
the main one to remain trust minimized. Who's idea was this?

Egregious entitlement for free marketing services on behalf of trusted
third parties done so by and on ETC branded platforms and communication
channels. I'm facing a lack of integrity for the platform these trusted
third party devs and projects are built on, inviting unnecessary potential
scams and security holes onto the officially branded website!

*Alternatives you tried*

Doing it myself, successfully creating my own accounts, using actual plans,
data, and tools not winging my marketing, adding potential security risks,
misleading end users! I've had incredible success regarding doing this on
my own measured with the KPIs that matter. Not amount of followers.

Christ, Look at Donald. Donald has created probably dozens of successful
social media accounts, on his own dime, on his own time, for the sake of
the fucking blockchain, not the trusted third parties built on top of it. *And
it is completely unprofessional looking, off-strategy, appears to have no
sense of plan or direction besides look at this project, oh and did you
notice its displayed on a platform called ETC_Network. Completely
misleading and disingenuous imo. Not to mention this likely breaks several
of Twitter's own term's and policies.... specifically hmmmm account /
platform manipulation!*

I just fucking did. Do it yourself or pay someone to do it for your private
project. For fucks sake need I say more about Donald, Etherplan, Tokenhash,
immmutable samourai, etclogic and all the successful KPIs he's driven to
this project on his own dime and own time? Show this project some respect
and stop using any ETC branded asset for your project's sake. This makes me
utterly sick to my stomach. Hey lets just add a list of internet people who
we trust to be kind and forsake any self interest and list them on the
fucking official website, not some little marketing channel, the goddamn
branded, official website! Wouldn't that be a great idea.

Em dom., 25 de set. de 2022 12:00, @classic_kevin ***@***.***>
escreveu:

**Comment by Bolsa-BOMS** [comment]
Thanks for sharing your experience and analysis. I really came from a trajectory where everything is very serious. Very serious. But people are educated from childhood to futility. I'm very happy that you guys created an element that I was prevented from creating. Here, in creating something serious for the world, I was called crazy. They really tried to get me in. I won judges and defense. But only They left me free. My innovation budget got stuck in the city I was born in.  When you can, please pay attention to the BOMS patent. We can amplify invention collectively. If you want. I do not speak English. But my son is your neighbor. He is studying an MBA at Harvard in California. I want to present to you 7 procedures that meet Brazilian compliance to feed the world. But at the same time it is a modal guide to create Biocapitalism with art! And now, with you! Blockchain and cryptocurrency. It's in the pre-export requirement. Exporting ideas.It is in the environmental requirement of the pre-analysis. It is in the requirement of Art, when it is visionary.But it's not that simple. By doing the biosync, from the market, with art, a series of enemies rise against it. Authorities addicted to corruption and etc.So... It's a secret project! Anyway. I need a Github in Portuguese. And I promise I'm already studying programming.  

Isadora Solon autora de BOMS
Wats 67981157770

Ricardo, meu filho, +1 (510) 977-3536

**Comment by developerkevin** [comment]
th 

> Also please don't pin issues like this unilaterally if this is your first contribution.
> 
> ![image](https://user-images.githubusercontent.com/1696942/192177066-af9dcb75-2bbb-4edf-8bfa-398adbd18e0e.png)

yes dear leader.
